language: node_js
node_js:
  - "4"
  - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblog4cxx10-dev
script: node test.js
